name: Build-Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: build and test
        run: |
          cd src
          dotnet test --filter TestCategory!=Integration
